### PR TITLE
fix: dates for 2081

### PR DESCRIPTION
**Pull request by RehmatFalcon**
Some of the dates were wrong for 2081.

| Month| ❌ Wrong Month Days | ✅ Correct Month Days |
|--------|--------|--------|
| Jestha | 31 | 32 |
| Ashar | 32 | 31 |
| Falgun | 30 | 29 |
| Chaitra | 30 | 31 | 

I have added some tests for additional code as well.

### CODE REVIEW

**Review by mesaugat — APPROVED** [review]
Just skimmed through. Hopefully it is correct.

**Comment by mesaugat** [comment]
@RehmatFalcon Thanks for contributing!

**Comment by mesaugat** [comment]
@RehmatFalcon Published version 2.0.2

**Comment by RehmatFalcon** [comment]
> @RehmatFalcon Published version 2.0.2

Thank you @mesaugat

**Pull request merged**
